title: hoatadocs
description: documentation web
theme: just-the-docs

url: https://just-the-docs.github.io

favicon_ico: "/assets/images/something.ico"

search_enabled: true

color_scheme: dark

plugins:
  - jekyll-seo-tag

# SEO settings
title: "hoatadocs"
description: "hoata cotoro documentation website"
url: "https://docs.hoatacotoro.cc"