title: hoatadocs
description: hoatacotoro documentation for some of my projects
theme: just-the-docs

url: "https://docs.hoatacotoro.cc"
baseurl: ""

favicon_ico: "favicon.ico"

search_enabled: true
color_scheme: hoata

plugins:
  - jekyll-seo-tag

permalink: pretty